version: '3.8'
services:
  analytics-service:
    image: analytics-service:${project.version}
    ports:
      - "8081:8080"
  auth-service:
    image: auth-service:${project.version}
    ports:
      - "8082:8080"
  billing-service:
    image: billing-service:${project.version}
    ports:
      - "8083:8080"
  customer-service:
    image: customer-service:${project.version}
    ports:
      - "8084:8080"
  gateway:
    image: gateway:${project.version}
    ports:
      - "8080:8080"
  notification-service:
    image: notification-service:${project.version}
    ports:
      - "8085:8080"
  reservation-service:
    image: reservation-service:${project.version}
    ports:
      - "8086:8080"
  vehicle-service:
    image: vehicle-service:${project.version}
    ports:
      - "8087:8080"
